import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileExists } from "../fs/readTree";
import type { MigrationAudit } from "../plans/migrationAudit";
import { buildMigrationAudit } from "../plans/migrationAudit";
import type { ResolvedAgentMode } from "./agentMode";
import type { InstallProfile } from "./installProfile";
import { buildInstallFiles } from "./applyInit";

export interface MigratePlanOptions {
  packageRoot: string;
  targetRoot: string;
  agentMode: ResolvedAgentMode;
  installProfile?: InstallProfile;
}

export interface MigratePlanResult {
  status: "planned" | "blocked";
  targetRoot: string;
  path: string;
  blocker: string | null;
  created: boolean;
}

const planPath = "docs/fuckia/migration-plan.md";

export async function writeMigrationPlan(options: MigratePlanOptions): Promise<MigratePlanResult> {
  const absolutePlanPath = path.join(options.targetRoot, planPath);
  if (await fileExists(absolutePlanPath)) {
    return {
      status: "blocked",
      targetRoot: options.targetRoot,
      path: planPath,
      blocker: `${planPath} already exists.`,
      created: false
    };
  }

  const audit = await buildMigrationAudit(options.targetRoot, options.agentMode, options.installProfile ?? "full");
  const installFiles = await buildInstallFiles(options);
  const missing = installFiles
    .filter((file) => !audit.inventory.some((item) => item.path === file.relativePath && item.exists))
    .map((file) => file.relativePath);
  const existing = installFiles
    .filter((file) => audit.inventory.some((item) => item.path === file.relativePath && item.exists))
    .map((file) => file.relativePath);

  await mkdir(path.dirname(absolutePlanPath), { recursive: true });
  await writeFile(absolutePlanPath, renderMigrationPlan(audit, missing, existing), { encoding: "utf8", flag: "wx" });

  return {
    status: "planned",
    targetRoot: options.targetRoot,
    path: planPath,
    blocker: null,
    created: true
  };
}

function renderMigrationPlan(audit: MigrationAudit, missing: string[], existing: string[]): string {
  return [
    "# Fuckia Migration Plan",
    "",
    "This plan is generated by `fuckia migrate --plan`.",
    "",
    "## Target",
    "",
    `- root: \`${audit.targetRoot}\``,
    `- agent mode: \`${audit.agentMode}\``,
    `- install profile: \`${audit.installProfile}\``,
    "- mode: warning",
    "- product code changes: forbidden",
    "",
    "## Existing Governance Inventory",
    "",
    ...audit.inventory.map((item) => `- ${item.exists ? "present" : "missing"}: \`${item.path}\` (${item.kind})`),
    "",
    "## Files To Create Directly",
    "",
    ...(missing.length > 0 ? missing.map((file) => `- \`${file}\``) : ["- None"]),
    "",
    "## Existing Files Requiring Merge Proposal",
    "",
    ...(existing.length > 0 ? existing.map((file) => `- \`${file}\``) : ["- None"]),
    "",
    "## Rules",
    "",
    "- Do not modify product code.",
    "- Do not overwrite existing governance files.",
    "- Preserve existing `AGENTS.md` and `CLAUDE.md` until merge proposals are reviewed.",
    "- Keep warning mode until GitHub and Linear gates are configured.",
    "- Run `fuckia migrate --apply` only after reviewing this plan.",
    ""
  ].join("\n");
}
